export {
  // Primary companion object exports
  Edit,
  type Origin,
  type EditOrigin,
  Epoch,
  Boundary,
  type EpochBoundary,
  Summary,
  type EpochIndex,
  History,
  type EpochTree,
  type Snapshot,
  // Deprecated backwards-compat re-exports
  edit,
  openBoundary,
  closedBoundary,
  snapshottedBoundary,
  epoch,
  appendEdit,
  isOpen,
  closeEpoch,
  snapshotEpoch,
  Sum,
  MinMax,
  SetUnion,
  summaryMonoid,
  epochIndexMonoid,
  epochMeasured,
  fromEpochs,
  emptyTree,
  fromSnapshots,
  backfillEdits,
  splitEpochAtSnapshot,
  mergeEpochs,
  mergeAdjacentInTree,
} from "./history/index.js";
